esphome:
  name: cat-scale
  friendly_name: cat-scale

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Cat-Scale Fallback Hotspot"
    password: !secret wifi_password

captive_portal:

globals:
  - id: zero_offset_left
    type: float
    restore_value: yes
    initial_value: '0'

  - id: zero_offset_right
    type: float
    restore_value: yes
    initial_value: '0'

button:
  ## Button used to initiate a manual tare
  - platform: template
    id: smart_scale_manual_tare_action_switch
    name: "Smart Scale Manual Tare Action"
    icon: mdi:scale-balance
    on_press:
      - lambda: |-
          id(zero_offset_left) = id(left).state;
          id(zero_offset_right) = id(right).state;

sensor:
  - platform: template
    id: sensor_zero_offset_left
    name: "Left Load Cell Zero Offset"
    lambda: |-
      return id(zero_offset_left);
    update_interval: 1s

  - platform: template
    id: sensor_zero_offset_right
    name: "Right Load Cell Zero Offset"
    lambda: |-
      return id(zero_offset_right);
    update_interval: 1s

  - platform: hx711
    name: "HX711 Left"
    id: left
    internal: True
    dout_pin: GPIO4
    clk_pin: GPIO2
    gain: 128
    update_interval: 0.1s
    filters:
      - quantile:
          window_size: 20
          send_every: 5
          send_first_at: 5
          quantile: .75
      - calibrate_linear:
          - 113800 -> 0
          - 557000 -> 2.042
    accuracy_decimals: 3

  - platform: hx711
    name: "HX711 Right"
    id: right
    internal: True
    dout_pin: GPIO19
    clk_pin: GPIO18
    gain: 128
    update_interval: 0.1s
    filters:
      - quantile:
          window_size: 20
          send_every: 5
          send_first_at: 5
          quantile: .75
      - calibrate_linear:
          - 15200 -> 0
          - 456000 -> 2.042
    accuracy_decimals: 3

  - platform: template
    name: "weight"
    lambda: |-
      return (id(left).state + id(right).state - id(zero_offset_left) - id(zero_offset_right));
    filters:
      - or:
        - throttle: 60s
        - delta: 0.01
    update_interval: 0.5s
    unit_of_measurement: kg
    accuracy_decimals: 2
